# Generated by Django 4.2.7 on 2025-10-04 10:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_timetableslot_notification_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timetableslot",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("monday", "Monday"),
                    ("tuesday", "Tuesday"),
                    ("wednesday", "Wednesday"),
                    ("thursday", "Thursday"),
                    ("friday", "Friday"),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Slide",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="slides/"),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, help_text="External image URL", null=True
                    ),
                ),
                (
                    "link_url",
                    models.URLField(
                        blank=True, help_text="Link when slide is clicked", null=True
                    ),
                ),
                ("button_text", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "slide_type",
                    models.CharField(
                        choices=[
                            ("banner", "Banner"),
                            ("carousel", "Carousel"),
                            ("promotion", "Promotion"),
                            ("announcement", "Announcement"),
                        ],
                        default="banner",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order (lower numbers first)"
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When to start showing this slide",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When to stop showing this slide",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "order"],
                        name="api_slide_is_acti_5e9902_idx",
                    ),
                    models.Index(
                        fields=["slide_type"], name="api_slide_slide_t_09316d_idx"
                    ),
                ],
            },
        ),
    ]
