# Generated by Django 4.2.7 on 2025-10-04 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_timetableslot_day_of_week_slide"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="message",
        ),
        migrations.RemoveField(
            model_name="timetableslot",
            name="instructor_name",
        ),
        migrations.AddField(
            model_name="article",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="articles/"),
        ),
        migrations.AddField(
            model_name="article",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="read_time",
            field=models.IntegerField(
                default=5, help_text="Estimated read time in minutes"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="share_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="published",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="body",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="notification",
            name="link",
            field=models.URLField(
                blank=True, help_text="Link when notification is clicked", null=True
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="slide",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="api.slide",
            ),
        ),
        migrations.AddField(
            model_name="slide",
            name="background_gradient",
            field=models.CharField(
                blank=True, help_text="CSS gradient class", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="timetableslot",
            name="class_type",
            field=models.CharField(
                choices=[
                    ("lecture", "Lecture"),
                    ("tutorial", "Tutorial"),
                    ("practical", "Practical"),
                    ("seminar", "Seminar"),
                    ("exam", "Exam"),
                ],
                default="lecture",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="timetableslot",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timetableslot",
            name="instructor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="timetableslot",
            name="academic_year",
            field=models.CharField(default="2024", max_length=10),
        ),
        migrations.AlterField(
            model_name="timetableslot",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetable_slots",
                to="api.course",
            ),
        ),
    ]
