# Generated by Django 4.2.7 on 2025-10-04 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_remove_notification_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timetableslot",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timetable_slots",
                to="api.course",
            ),
        ),
    ]
