# Generated by Django 4.2.7 on 2025-10-04 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_timetableslot_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetableslot",
            name="student_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timetable_slots",
                to="api.studentcourse",
            ),
        ),
    ]
