# Generated by Django 4.2.7 on 2025-10-04 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_timetableslot_student_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("General Inquiry", "General Inquiry"),
                            ("Account & Login", "Account & Login"),
                            ("Timetable Help", "Timetable Help"),
                            ("GPA Calculator", "GPA Calculator"),
                            ("Bug Report", "Bug Report"),
                            ("Feature Request", "Feature Request"),
                        ],
                        max_length=200,
                    ),
                ),
                ("message", models.TextField()),
                ("user_email", models.EmailField(max_length=254)),
                ("user_name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "ticket_number",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                ("admin_response", models.TextField(blank=True, null=True)),
                ("admin_responded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="help_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="api_helpmes_status_92f496_idx",
                    ),
                    models.Index(
                        fields=["user_email"], name="api_helpmes_user_em_7b58e8_idx"
                    ),
                    models.Index(
                        fields=["ticket_number"], name="api_helpmes_ticket__c64d36_idx"
                    ),
                ],
            },
        ),
    ]
