# Generated by Django 4.2.7 on 2025-10-10 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_universityambassador"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmbassadorMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("completed", "Completed"),
                        ],
                        default="sent",
                        max_length=10,
                    ),
                ),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to="api.universityambassador",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_ambassador_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["sender", "-created_at"],
                        name="api_ambassa_sender__79145a_idx",
                    ),
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="api_ambassa_recipie_aae4fc_idx",
                    ),
                    models.Index(
                        fields=["status"], name="api_ambassa_status_9b058e_idx"
                    ),
                    models.Index(
                        fields=["priority"], name="api_ambassa_priorit_3af030_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AmbassadorActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned to University"),
                            ("message_sent", "Message Sent"),
                            ("message_received", "Message Received"),
                            ("login", "Login"),
                            ("profile_updated", "Profile Updated"),
                            ("university_joined", "Joined University"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ambassador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="api.universityambassador",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["ambassador", "-created_at"],
                        name="api_ambassa_ambassa_fa885c_idx",
                    ),
                    models.Index(
                        fields=["activity_type"], name="api_ambassa_activit_480e88_idx"
                    ),
                ],
            },
        ),
    ]
