# Generated by Django 4.2.7 on 2025-10-18 14:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_ambassadormessage_ambassadoractivity"),
    ]

    operations = [
        migrations.CreateModel(
            name="UniversityLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("url", models.URLField()),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "university_id",
                    models.CharField(
                        help_text="University identifier (e.g., 'udsm')", max_length=50
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["university_id"], name="api_univers_univers_f21b9e_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="api_univers_is_acti_a007b4_idx"
                    ),
                ],
            },
        ),
    ]
