# Generated by Django 4.2.7 on 2025-10-18 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_add_university_link"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="universitylink",
            name="api_univers_univers_f21b9e_idx",
        ),
        migrations.RemoveField(
            model_name="universitylink",
            name="university_id",
        ),
        migrations.AddField(
            model_name="universitylink",
            name="university",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links",
                to="api.university",
            ),
        ),
        migrations.AddIndex(
            model_name="universitylink",
            index=models.Index(
                fields=["university"], name="api_univers_univers_f21b9e_idx"
            ),
        ),
    ]
