# Generated by Django 4.2.7 on 2025-10-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_modify_university_link_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="firebase_uid",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
