# Generated by Django 4.2.7 on 2025-11-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_user_firebase_uid_user_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hobbies",
            field=models.JSONField(
                blank=True, default=list, help_text="List of hobby IDs"
            ),
        ),
    ]
