# Generated by Django 4.2.7 on 2025-11-19 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_user_hobbies"),
    ]

    operations = [
        migrations.CreateModel(
            name="GPACalculation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gpa",
                    models.DecimalField(
                        decimal_places=2, help_text="GPA value", max_digits=3
                    ),
                ),
                ("semester", models.IntegerField(help_text="Semester number (1 or 2)")),
                (
                    "academic_year",
                    models.IntegerField(help_text="Academic year (1, 2, 3, etc.)"),
                ),
                (
                    "is_target",
                    models.BooleanField(
                        default=False,
                        help_text="True if this is a target GPA calculation",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gpa_calculations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="api_gpacalc_user_id_1818c7_idx",
                    ),
                    models.Index(
                        fields=["semester", "academic_year"],
                        name="api_gpacalc_semeste_953fc7_idx",
                    ),
                    models.Index(
                        fields=["is_target"], name="api_gpacalc_is_targ_2c64d2_idx"
                    ),
                ],
            },
        ),
    ]
