# Generated by Django 4.2.7 on 2025-12-17 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_gpacalculation"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("login_time", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                (
                    "login_type",
                    models.CharField(
                        choices=[
                            ("email", "Email/Password"),
                            ("firebase", "Firebase"),
                            ("jwt_refresh", "JWT Refresh"),
                            ("admin", "Admin Dashboard"),
                        ],
                        default="email",
                        max_length=20,
                    ),
                ),
                ("success", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Login Activities",
                "ordering": ["-login_time"],
                "indexes": [
                    models.Index(
                        fields=["user", "-login_time"],
                        name="api_loginac_user_id_44f18b_idx",
                    ),
                    models.Index(
                        fields=["-login_time"], name="api_loginac_login_t_48fdec_idx"
                    ),
                    models.Index(
                        fields=["login_type"], name="api_loginac_login_t_41e4dd_idx"
                    ),
                    models.Index(
                        fields=["success"], name="api_loginac_success_555bef_idx"
                    ),
                ],
            },
        ),
    ]
