# Generated by Django 6.0.7 on 2026-07-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_encrypt_gpa_values_and_remove_plaintext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpacalculation',
            name='gpa_alg',
            field=models.CharField(blank=True, default='AES-GCM-PBKDF2', help_text='Client-side encryption algorithm metadata', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gpacalculation',
            name='gpa_ciphertext',
            field=models.TextField(blank=True, default='', help_text='Encrypted GPA payload (base64 ciphertext)', null=True),
        ),
        migrations.AlterField(
            model_name='gpacalculation',
            name='gpa_iv',
            field=models.CharField(blank=True, default='', help_text='Base64 IV/nonce used for encryption', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='gpacalculation',
            name='gpa_salt',
            field=models.CharField(blank=True, default='', help_text='Base64 salt used for key derivation', max_length=128, null=True),
        ),
    ]
