# Generated by Django 5.2.3 on 2026-08-27
# Adds the profile-enrichment fields on api.User and the feedback fields on
# api.GPACalculation that the model definitions declare but the preceding
# migration lineage never created. Pure additive operations; existing data is
# untouched and pre-populated rows receive the defaults.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_alter_gpacalculation_gpa_alg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, help_text="Short bio/about me", max_length=500),
        ),
        migrations.AddField(
            model_name="user",
            name="public_profile",
            field=models.BooleanField(default=True, help_text="Make profile visible to others"),
        ),
        migrations.AddField(
            model_name="user",
            name="show_email",
            field=models.BooleanField(default=False, help_text="Show email on public profile"),
        ),
        migrations.AddField(
            model_name="user",
            name="show_phone",
            field=models.BooleanField(default=False, help_text="Show phone on public profile"),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_verified",
            field=models.BooleanField(default=False, help_text="Phone number verified via OTP"),
        ),
        migrations.AddField(
            model_name="user",
            name="social_links",
            field=models.JSONField(blank=True, default=dict, help_text="LinkedIn, Twitter, etc."),
        ),
        migrations.AddField(
            model_name="user",
            name="achievements",
            field=models.JSONField(blank=True, default=list, help_text="Badges, awards, achievements"),
        ),
        migrations.AddField(
            model_name="user",
            name="tokens_balance",
            field=models.DecimalField(decimal_places=0, default=0, help_text="Cached token balance", max_digits=10),
        ),
        migrations.AddField(
            model_name="gpacalculation",
            name="feedback",
            field=models.TextField(blank=True, help_text="User's explanation of GPA result vs expectation"),
        ),
        migrations.AddField(
            model_name="gpacalculation",
            name="feedback_tokens_awarded",
            field=models.IntegerField(default=0, help_text="Tokens awarded for providing feedback"),
        ),
        migrations.AddField(
            model_name="gpacalculation",
            name="is_planned",
            field=models.BooleanField(default=False, help_text="Was this a planned/target GPA calculation?"),
        ),
        migrations.AddField(
            model_name="gpacalculation",
            name="planned_gpa_value",
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Target GPA if planned", max_digits=3, null=True),
        ),
    ]