# Generated by Django 5.2.3 on 2026-08-28 11:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_user_profile_and_gpa_feedback_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='grade_scheme',
            field=models.CharField(choices=[('grades', 'Letter grades (A, B+, B...)'), ('marks', 'Marks (0-100)')], default='grades', help_text='How grades are entered/computed for this university', max_length=10),
        ),
        migrations.AddField(
            model_name='university',
            name='grade_scheme_config',
            field=models.JSONField(blank=True, default=dict, help_text="Optional per-university grading configuration. For 'grades': {'letter_points': {'A':5,'B+':4,'B':3,'C':2,'D':1,'E':0}}. For 'marks': {'max_marks':100,'pass_mark':40,'thresholds':[[70,0.2,-10.5],...]} where each row is [min_marks, slope, intercept] mapping marks to points."),
        ),
        migrations.CreateModel(
            name='StudentTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.IntegerField(help_text='Academic year (1, 2, 3, ...)')),
                ('semester', models.IntegerField(help_text='Semester (1 or 2)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='api.student')),
            ],
            options={
                'ordering': ['academic_year', 'semester'],
                'unique_together': {('student', 'academic_year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='StudentCourseEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('credits', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('core', 'Core'), ('elective', 'Elective')], default='core', max_length=10)),
                ('grade', models.CharField(blank=True, help_text="Letter grade e.g. 'A', 'B+'", max_length=4, null=True)),
                ('marks', models.IntegerField(blank=True, help_text='Raw marks (0-100) for marks-based schemes', null=True)),
                ('points', models.DecimalField(blank=True, decimal_places=2, help_text='Grade point value (0.00-5.00)', max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_enrollments', to='api.course')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.studentterm')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('term', 'code')},
            },
        ),
    ]
