# Generated by Django 5.2.17 on 2026-09-02 06:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_normalize_student_courses_periods'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    'article',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='user_likes',
                        to='api.article',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='liked_articles',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'unique_together': {('article', 'user')},
                'indexes': [
                    models.Index(
                        fields=['article', 'user'],
                        name='api_article_article_5d35bf_idx',
                    ),
                ],
            },
        ),
    ]