# Generated by Django 5.2.3 on 2025-11-08 18:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_user_firebase_uid_user_profile_picture"),
        ("chatbot", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "query_intent",
                    models.CharField(
                        blank=True,
                        help_text="Detected intent of queries",
                        max_length=100,
                    ),
                ),
                (
                    "common_topics",
                    models.JSONField(
                        default=list, help_text="List of common topics discussed"
                    ),
                ),
                (
                    "knowledge_gaps",
                    models.JSONField(
                        default=list, help_text="Queries that couldn't be answered well"
                    ),
                ),
                (
                    "avg_response_time",
                    models.FloatField(
                        default=0.0, help_text="Average response time in seconds"
                    ),
                ),
                ("total_api_calls", models.IntegerField(default=0)),
                ("total_cache_hits", models.IntegerField(default=0)),
                (
                    "avg_rating",
                    models.FloatField(default=0.0, help_text="Average feedback rating"),
                ),
                ("feedback_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "Very Poor"),
                            (2, "Poor"),
                            (3, "Neutral"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ],
                        help_text="User rating of the response",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, help_text="Optional user comment"),
                ),
                ("query", models.TextField(help_text="Original user query")),
                (
                    "response",
                    models.TextField(help_text="Chatbot response that was rated"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteNavigation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Feature or page name", max_length=200),
                ),
                (
                    "route",
                    models.CharField(
                        help_text="Route path (e.g., /app/timetable)", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of what this feature does"),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated keywords for search",
                        max_length=500,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon name or identifier", max_length=100
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="knowledgedocument",
            options={"ordering": ["-priority", "-usage_count", "-created_at"]},
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this document is active and searchable"
            ),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="priority",
            field=models.IntegerField(
                default=5, help_text="Priority score 1-10 (higher = more important)"
            ),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated tags for better searchability",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="usage_count",
            field=models.IntegerField(
                default=0, help_text="Number of times this document has been retrieved"
            ),
        ),
        migrations.AlterField(
            model_name="knowledgedocument",
            name="category",
            field=models.CharField(
                choices=[
                    ("faq", "FAQ"),
                    ("policy", "Policy"),
                    ("guide", "Guide"),
                    ("schedule", "Schedule Info"),
                    ("regulation", "Regulation"),
                    ("procedure", "Procedure"),
                    ("calendar", "Calendar Event"),
                    ("navigation", "Navigation"),
                    ("academic_advice", "Academic Advice"),
                    ("program_info", "Program Information"),
                ],
                default="faq",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(
                fields=["category", "university", "is_active"],
                name="chatbot_kno_categor_383ae6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(
                fields=["priority", "usage_count"],
                name="chatbot_kno_priorit_d42ee9_idx",
            ),
        ),
        migrations.AddField(
            model_name="conversationanalytics",
            name="conversation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics",
                to="chatbot.conversation",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="chatbot.conversation",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="knowledge_documents_used",
            field=models.ManyToManyField(
                blank=True,
                help_text="Knowledge documents used in this response",
                to="chatbot.knowledgedocument",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="chatbot.message",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chatbot_feedback",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="sitenavigation",
            index=models.Index(
                fields=["route", "is_active"], name="chatbot_sit_route_5939eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["user", "rating", "created_at"],
                name="chatbot_fee_user_id_164670_idx",
            ),
        ),
    ]
