# Generated by Django 5.2.17 on 2026-09-01 07:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_normalize_student_courses_periods'),
        ('chatbot', '0002_conversationanalytics_feedback_sitenavigation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='mode',
            field=models.CharField(choices=[('bot', 'Bot'), ('admin_copilot', 'Admin Co-pilot')], default='bot', max_length=20),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='embedding',
            field=models.BinaryField(blank=True, help_text='Precomputed sentence embedding (float32 bytes)', null=True),
        ),
        migrations.CreateModel(
            name='ConversationAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attachment_type', models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('voice', 'Voice')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='chatbot_attachments/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chatbot.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='ConversationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='chatbot_docs/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('attachment_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('txt', 'Text'), ('image', 'Image')], max_length=20)),
                ('extracted_text', models.TextField(blank=True, help_text='Extracted text for RAG')),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='chatbot.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_hash', models.CharField(db_index=True, help_text='SHA256 of normalized query', max_length=64)),
                ('query_text', models.TextField()),
                ('response_text', models.TextField(blank=True)),
                ('trigger', models.CharField(choices=[('no_kb_result', 'No Knowledge Base Result'), ('low_confidence', 'Low Confidence Answer'), ('negative_rating', 'Negative User Rating'), ('duplicate_flagged', 'Duplicate Flagged')], max_length=30)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.conversation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suggestions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'trigger'], name='chatbot_kno_status_51e2ed_idx'), models.Index(fields=['query_hash'], name='chatbot_kno_query_h_b82aad_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(choices=[('goal', 'Goal'), ('stressor', 'Stressor'), ('preference', 'Preference'), ('running_joke', 'Running Joke'), ('habit', 'Habit'), ('context', 'Context')], max_length=50)),
                ('value', models.TextField()),
                ('confidence', models.FloatField(default=0.5, help_text='0-1, how sure are we this is durable')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_referenced_at', models.DateTimeField(auto_now=True)),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.message')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='api.student')),
            ],
            options={
                'ordering': ['-confidence', '-last_referenced_at'],
                'indexes': [models.Index(fields=['student', 'is_active', 'key'], name='chatbot_stu_student_32959b_idx')],
            },
        ),
    ]
