# Generated by Django 5.2.17 on 2026-10-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_add_articlelike_model'),
        ('chatbot', '0003_conversation_mode_knowledgedocument_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='source_attribution',
            field=models.CharField(blank=True, help_text="Who published it, e.g. 'Faculty of Engineering' or 'Student Government'. Used to phrase the answer naturally, e.g. 'based on the clarification communicated to students'.", max_length=200),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='source_level',
            field=models.CharField(choices=[('official', 'Official / Primary (regulation, policy, official fee schedule)'), ('official_communication', 'Official Communication (authorised University office)'), ('trusted_clarification', 'Trusted Supporting Clarification (student-leader / student-government)'), ('general', 'General Information (guidance, community info)')], db_index=True, default='official', help_text='Authority of the source. Controls how firmly Mr Caluu presents it.', max_length=30),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['source_level', 'is_active'], name='chatbot_kno_source__935d02_idx'),
        ),
    ]
