# Generated by Django 5.2.17 on 2026-10-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_knowledgedocument_source_attribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgesuggestion',
            name='source_level',
            field=models.CharField(choices=[('official', 'Official / Primary'), ('official_communication', 'Official Communication'), ('trusted_clarification', 'Trusted Supporting Clarification (student leader)'), ('general', 'General Information')], default='general', help_text='Authority assigned when this suggestion is approved and becomes a KnowledgeDocument.', max_length=30),
        ),
    ]
