# Generated by Django 4.2.7 on 2025-10-18 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_ambassadormessage_ambassadoractivity"),
        ("resources_opps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="university",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resources",
                to="api.university",
            ),
        ),
    ]
