# Generated by Django 4.2.7 on 2025-11-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_opps", "0002_modify_resource_university_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="opportunity",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="opportunity",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
