# Generated by Django 5.2.3 on 2026-08-27 17:44

import caluu_map.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0025_alter_gpacalculation_gpa_alg_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[caluu_map.validators.validate_latitude])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[caluu_map.validators.validate_longitude])),
                ('boundary', models.JSONField(blank=True, help_text='GeoJSON Polygon/MultiPolygon describing the campus boundary.', null=True, validators=[caluu_map.validators.validate_geojson_polygon])),
                ('is_active', models.BooleanField(default=True)),
                ('university', models.ForeignKey(help_text='The existing Caluu+ University this campus belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='api.university')),
            ],
            options={
                'verbose_name_plural': 'Campuses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, default='', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[caluu_map.validators.validate_latitude])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[caluu_map.validators.validate_longitude])),
                ('geometry', models.JSONField(blank=True, help_text='GeoJSON Polygon/MultiPolygon footprint of the building.', null=True)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('accessibility_information', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='caluu_map.campus')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CampusContributor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('contributor', 'Contributor'), ('moderator', 'Moderator'), ('campus_admin', 'Campus Admin')], default='viewer', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='caluu_map.campus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_contributorships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['campus__name', 'user__display_name'],
            },
        ),
        migrations.CreateModel(
            name='PathNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[caluu_map.validators.validate_latitude])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[caluu_map.validators.validate_longitude])),
                ('node_type', models.CharField(choices=[('walkway', 'Walkway'), ('entrance', 'Entrance'), ('stairs', 'Stairs'), ('elevator', 'Elevator'), ('corridor', 'Corridor'), ('road', 'Road'), ('landmark', 'Landmark')], default='walkway', max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_nodes', to='caluu_map.campus')),
            ],
            options={
                'ordering': ['campus_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PathEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distance', models.DecimalField(decimal_places=3, max_digits=12)),
                ('geometry', models.JSONField(blank=True, help_text='GeoJSON LineString describing the actual route between the two nodes.', null=True)),
                ('bidirectional', models.BooleanField(default=True)),
                ('accessibility', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_edges', to='caluu_map.campus')),
                ('end_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='caluu_map.pathnode')),
                ('start_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='caluu_map.pathnode')),
            ],
            options={
                'ordering': ['campus_id', 'distance'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('type', models.CharField(choices=[('office', 'Office'), ('lecture_hall', 'Lecture Hall'), ('laboratory', 'Laboratory'), ('library', 'Library'), ('cafeteria', 'Cafeteria'), ('hostel', 'Hostel'), ('auditorium', 'Auditorium'), ('atm', 'ATM'), ('parking', 'Parking'), ('clinic', 'Clinic'), ('sports_ground', 'Sports Ground'), ('gate', 'Gate'), ('prayer_area', 'Prayer Area'), ('other', 'Other')], default='other', max_length=30)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[caluu_map.validators.validate_latitude])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[caluu_map.validators.validate_longitude])),
                ('floor', models.CharField(blank=True, default='', max_length=50)),
                ('room_number', models.CharField(blank=True, default='', max_length=50)),
                ('opening_hours', models.TextField(blank=True, default='')),
                ('contact_information', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('building', models.ForeignKey(blank=True, help_text='Optional parent building. May be empty for places not tied to a building.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='caluu_map.building')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='caluu_map.campus')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='Upload an image file (JPEG, PNG, WEBP, GIF).', upload_to='map/photos/%Y/%m/', validators=[caluu_map.validators.validate_photo_file])),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='caluu_map.building')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='caluu_map.campus')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_photos', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='caluu_map.place')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportCorrection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('campus', 'Campus'), ('building', 'Building'), ('place', 'Place'), ('photo', 'Photo'), ('path_node', 'Path Node'), ('path_edge', 'Path Edge'), ('other', 'Other')], max_length=20)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.TextField(help_text='What is incorrect or missing.')),
                ('proposed_correction', models.JSONField(blank=True, help_text='Optional structured proposal (fields the user suggests).', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_reports', to='caluu_map.campus')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_correction_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_corrections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.BigIntegerField()),
                ('entity_type', models.CharField(choices=[('campus', 'Campus'), ('building', 'Building'), ('place', 'Place'), ('photo', 'Photo'), ('path_node', 'Path Node'), ('path_edge', 'Path Edge')], max_length=20)),
                ('object_id', models.UUIDField()),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], default='updated', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_changes', to='caluu_map.campus')),
            ],
            options={
                'ordering': ['version'],
            },
        ),
        migrations.CreateModel(
            name='SyncVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_version', to='caluu_map.campus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='campus',
            index=models.Index(fields=['university', 'latitude', 'longitude'], name='campus_point_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['campus', 'latitude', 'longitude'], name='building_point_idx'),
        ),
        migrations.AddConstraint(
            model_name='building',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('campus', 'code'), name='uniq_building_code_per_campus'),
        ),
        migrations.AddConstraint(
            model_name='campuscontributor',
            constraint=models.UniqueConstraint(fields=('user', 'campus'), name='uniq_contributor_per_campus'),
        ),
        migrations.AddIndex(
            model_name='pathnode',
            index=models.Index(fields=['campus', 'latitude', 'longitude'], name='pathnode_point_idx'),
        ),
        migrations.AddIndex(
            model_name='pathnode',
            index=models.Index(fields=['campus', 'node_type'], name='pathnode_type_idx'),
        ),
        migrations.AddIndex(
            model_name='pathedge',
            index=models.Index(fields=['campus', 'start_node', 'end_node'], name='path_edge_pair_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['campus', 'type'], name='place_type_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['campus', 'latitude', 'longitude'], name='place_point_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['campus', 'is_active'], name='photo_campus_idx'),
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('building__isnull', False), ('place__isnull', True)), models.Q(('building__isnull', True), ('place__isnull', False)), _connector='OR'), name='photo_has_exactly_one_target'),
        ),
        migrations.AddIndex(
            model_name='reportcorrection',
            index=models.Index(fields=['campus', 'status'], name='report_status_idx'),
        ),
        migrations.AddIndex(
            model_name='syncchange',
            index=models.Index(fields=['campus', 'version'], name='sync_version_idx'),
        ),
    ]
