# Generated by Django 5.2.3 on 2026-09-02 15:40

import caluu_map.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caluu_map', '0002_venue_and_moderation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, validators=[caluu_map.validators.validate_latitude]),
        ),
        migrations.AlterField(
            model_name='building',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, validators=[caluu_map.validators.validate_longitude]),
        ),
        migrations.AlterField(
            model_name='campus',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, validators=[caluu_map.validators.validate_latitude]),
        ),
        migrations.AlterField(
            model_name='campus',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, validators=[caluu_map.validators.validate_longitude]),
        ),
        migrations.AlterField(
            model_name='pathnode',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, validators=[caluu_map.validators.validate_latitude]),
        ),
        migrations.AlterField(
            model_name='pathnode',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, validators=[caluu_map.validators.validate_longitude]),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, validators=[caluu_map.validators.validate_latitude]),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, validators=[caluu_map.validators.validate_longitude]),
        ),
        migrations.AlterField(
            model_name='venue',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, validators=[caluu_map.validators.validate_latitude]),
        ),
        migrations.AlterField(
            model_name='venue',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, validators=[caluu_map.validators.validate_longitude]),
        ),
    ]
