# Generated by Django 5.2.17 on 2026-09-09 07:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch', models.CharField(default='main', max_length=64)),
                ('commit_before', models.CharField(blank=True, default='', max_length=40)),
                ('commit_after', models.CharField(blank=True, default='', max_length=40)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('rolled_back', 'Rolled Back'), ('failed', 'Failed')], db_index=True, default='running', max_length=20)),
                ('trigger', models.CharField(choices=[('timer', 'Timer'), ('manual', 'Manual')], default='timer', max_length=16)),
                ('log', models.TextField(blank=True, default='')),
                ('error_summary', models.TextField(blank=True, default='')),
                ('db_backup_path', models.CharField(blank=True, default='', help_text='SQLite snapshot taken before migrations, used for rollback.', max_length=512)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Deployment',
                'verbose_name_plural': 'Deployments',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', '-started_at'], name='deployments_status_1dad60_idx')],
            },
        ),
    ]
