# Generated by Django 5.2.17 on 2026-08-30 07:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0030_normalize_student_courses_periods'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.CharField(help_text='e.g. 2024/2025', max_length=20)),
                ('semester', models.CharField(default='Semester 1', help_text='e.g. Semester 1, Semester 2', max_length=50)),
                ('start_date', models.DateField(help_text='Semester start date. Used to derive semester weeks.')),
                ('end_date', models.DateField(help_text='Semester end date.')),
                ('is_active', models.BooleanField(default=True, help_text='Mark as the current calendar to be returned when no specific calendar is requested.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_calendars', to='api.university')),
            ],
            options={
                'verbose_name': 'Academic Calendar',
                'verbose_name_plural': 'Academic Calendars',
                'ordering': ['-is_active', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='AcademicEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('registration', 'Registration'), ('orientation', 'Orientation'), ('lectures', 'Lectures Begin'), ('mid_semester', 'Mid-Semester'), ('examination', 'Examinations'), ('break', 'Break'), ('holiday', 'Holiday'), ('results', 'Results'), ('graduation', 'Graduation'), ('academic', 'Academic'), ('other', 'Other')], default='academic', max_length=20)),
                ('start_date', models.DateField(help_text='Start date (YYYY-MM-DD). A single-day event only needs this.')),
                ('end_date', models.DateField(blank=True, help_text='End date (YYYY-MM-DD). Leave empty for a single-day/point event.', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0, help_text='Optional sort order within the timeline (lower first).')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive events are hidden from the timeline.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='academia.academiccalendar')),
            ],
            options={
                'verbose_name': 'Academic Event',
                'verbose_name_plural': 'Academic Events',
                'ordering': ['order', 'start_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='academiccalendar',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('university', 'academic_year', 'semester', 'is_active'), name='uniq_active_calendar_per_university'),
        ),
    ]
