# Generated by Django 5.2.17 on 2026-09-09 09:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MrCaluuMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='Message text with markdown-style bold (**bold**)')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('links', models.JSONField(blank=True, default=list)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MrCaluuSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotation_interval_seconds', models.IntegerField(blank=True, default=1800, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mr. Caluu Settings',
                'verbose_name_plural': 'Mr. Caluu Settings',
            },
        ),
    ]
