# Generated by Django 5.2.17 on 2026-09-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_features', '0002_mrcaluumessage_mrcaluusettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrcaluumessage',
            name='image',
            field=models.ImageField(blank=True, help_text='Uploaded image shown in the carousel', null=True, upload_to='mr_caluu/'),
        ),
        migrations.AlterField(
            model_name='mrcaluumessage',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL as a fallback', null=True),
        ),
    ]
