# Generated by Django 5.2.3 on 2026-08-27 22:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='Stable machine key, e.g. PROFILE_COMPLETION', max_length=64, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consumption Rule',
                'verbose_name_plural': 'Consumption Rules',
            },
        ),
        migrations.CreateModel(
            name='RewardRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='Stable machine key, e.g. PROFILE_COMPLETION', max_length=64, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reward Rule',
                'verbose_name_plural': 'Reward Rules',
            },
        ),
        migrations.CreateModel(
            name='TokenEconomyConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TokenPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('token_amount', models.DecimalField(decimal_places=0, help_text='Number of tokens delivered', max_digits=20)),
                ('price_amount', models.DecimalField(decimal_places=2, help_text='Price in configured currency', max_digits=12)),
                ('currency', models.CharField(default='TSH', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'token_amount'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='tokens_toke_is_acti_b2e3fd_idx')],
            },
        ),
        migrations.CreateModel(
            name='TokenWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('earned_balance', models.DecimalField(decimal_places=0, default=0, help_text='Current spendable EARNED token balance.', max_digits=20)),
                ('purchased_balance', models.DecimalField(decimal_places=0, default=0, help_text='Current spendable PURCHASED token balance.', max_digits=20)),
                ('earned_lifetime', models.DecimalField(decimal_places=0, default=0, help_text='Total EARNED tokens ever credited.', max_digits=20)),
                ('earned_redeemed', models.DecimalField(decimal_places=0, default=0, help_text='Total EARNED tokens that have left via redemption.', max_digits=20)),
                ('purchased_lifetime', models.DecimalField(decimal_places=0, default=0, help_text='Total PURCHASED tokens ever credited.', max_digits=20)),
                ('spent_lifetime', models.DecimalField(decimal_places=0, default=0, help_text='Total tokens ever consumed (both kinds).', max_digits=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the wallet can receive/send tokens.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The user who owns this wallet', on_delete=django.db.models.deletion.CASCADE, related_name='token_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('PROFILE_COMPLETION', 'Profile Completion'), ('OPPORTUNITY_REWARD', 'Opportunity Reward'), ('ARTICLE_REWARD', 'Article Reward'), ('ARTICLE_SHARE_REWARD', 'Article Share Reward'), ('SURVEY_REWARD', 'Survey Reward'), ('SURVEY_QUESTION_REWARD', 'Survey Question Reward'), ('REFERRAL_REWARD', 'Referral Reward'), ('TOKEN_PURCHASE', 'Token Purchase'), ('GPA_CONSUMPTION', 'GPA Consumption'), ('MR_CALUU_CONSUMPTION', 'Mr Caluu Consumption'), ('MAP_CONSUMPTION', 'Caluu Map Consumption'), ('TOKEN_REDEMPTION', 'Token Redemption'), ('REDEMPTION_RELEASE', 'Redemption Release'), ('REFUND', 'Refund'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment')], max_length=50)),
                ('kind', models.CharField(choices=[('earned', 'Earned'), ('purchased', 'Purchased')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=20)),
                ('earned_balance_after', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('purchased_balance_after', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('reference_key', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('initiated_by', models.CharField(blank=True, default='system', help_text='system, user, admin:<pk>', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, help_text='The admin/actor who performed the operation, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_token_transactions', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tokens.tokenwallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RedemptionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('earned_amount', models.DecimalField(decimal_places=0, max_digits=20)),
                ('payout_provider', models.CharField(blank=True, default='manual', max_length=50)),
                ('payout_target', models.CharField(blank=True, default='', help_text='e.g. phone number / account identifier', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('review_reason', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_redemptions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_redemptions', to=settings.AUTH_USER_MODEL)),
                ('finalize_transaction', models.ForeignKey(blank=True, help_text='Final deduction ledger entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_redemption', to='tokens.tokentransaction')),
                ('hold_transaction', models.ForeignKey(blank=True, help_text='Reservation/hold ledger entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holding_redemption', to='tokens.tokentransaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='tokens.tokenwallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('eligible', 'Eligible'), ('rewarded', 'Rewarded'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred', models.OneToOneField(help_text='The referred (new) user.', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_referral', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(help_text='The user who referred someone.', on_delete=django.db.models.deletion.CASCADE, related_name='issued_referrals', to=settings.AUTH_USER_MODEL)),
                ('reward_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tokens.tokentransaction')),
            ],
            options={
                'indexes': [models.Index(fields=['referrer'], name='tokens_refe_referre_a392d1_idx'), models.Index(fields=['code'], name='tokens_refe_code_3ecde8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tokenwallet',
            index=models.Index(fields=['user'], name='tokens_toke_user_id_18da20_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenwallet',
            index=models.Index(fields=['is_active'], name='tokens_toke_is_acti_dbba78_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransaction',
            index=models.Index(fields=['user', '-created_at'], name='tokens_toke_user_id_d5c229_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransaction',
            index=models.Index(fields=['transaction_type'], name='tokens_toke_transac_6a7a6c_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransaction',
            index=models.Index(fields=['kind'], name='tokens_toke_kind_e9d511_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransaction',
            index=models.Index(fields=['wallet'], name='tokens_toke_wallet__3f9c95_idx'),
        ),
        migrations.AddConstraint(
            model_name='tokentransaction',
            constraint=models.UniqueConstraint(fields=('user', 'reference_key'), name='uniq_tokentx_user_ref'),
        ),
        migrations.AddIndex(
            model_name='redemptionrequest',
            index=models.Index(fields=['user', '-created_at'], name='tokens_rede_user_id_d4102c_idx'),
        ),
        migrations.AddIndex(
            model_name='redemptionrequest',
            index=models.Index(fields=['status'], name='tokens_rede_status_ff7a63_idx'),
        ),
    ]
