# Generated by Django 5.2.17 on 2026-08-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokentransaction',
            name='transaction_type',
            field=models.CharField(choices=[('PROFILE_COMPLETION', 'Profile Completion'), ('OPPORTUNITY_REWARD', 'Opportunity Reward'), ('ARTICLE_REWARD', 'Article Reward'), ('ARTICLE_SHARE_REWARD', 'Article Share Reward'), ('SURVEY_REWARD', 'Survey Reward'), ('SURVEY_QUESTION_REWARD', 'Survey Question Reward'), ('COURSE_CONTRIBUTION', 'Course Contribution'), ('REFERRAL_REWARD', 'Referral Reward'), ('TOKEN_PURCHASE', 'Token Purchase'), ('GPA_CONSUMPTION', 'GPA Consumption'), ('MR_CALUU_CONSUMPTION', 'Mr Caluu Consumption'), ('MAP_CONSUMPTION', 'Caluu Map Consumption'), ('TOKEN_REDEMPTION', 'Token Redemption'), ('REDEMPTION_RELEASE', 'Redemption Release'), ('REFUND', 'Refund'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment')], max_length=50),
        ),
    ]
